apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: goservers
spec:
  selector:
    matchLabels:
      app: goservers
  replicas: 10
  template:
    metadata:
      labels:
        app: "goservers"
    spec:
      containers:
        - name: goservers
          image: "guilhermesilv/hello-go:latest"