apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: goservers
spec:
  selector:
    matchLabels:
      app: goservers
  replicas: 2
  template:
    metadata:
      labels:
        app: "goservers"
    spec:
      containers:
        - name: goservers
          image: "wesleywillians/hello-go:v5.4"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 2
            failureThreshold: 1
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8000
          #   periodSeconds: 2
          #   failureThreshold: 3
          #   timeoutSeconds: 10
          #   successThreshold: 1
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: mysecret
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: env-config-family
            items:
              - key: members
                path: "family.txt"


          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: env-config
          #         key: NAME
          #   - name: AGE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: env-config
          #         key: AGE


            # - name: NAME
            #   value: "Wesley"
            # - name: AGE
            #   value: "25"