version: '3'

services:
  laravel:
    build:
      context: laravel/
      dockerfile: Dockerfile.prod
    image: guilhermesilv/laravel:prod
    container_name: laravel
    networks:
      - laranet
  nginx:
    build:
      context: ngnix/
      dockerfile: Dockerfile.prod
    image: guilhermesilv/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"
networks:
  laranet:
    driver: bridge